#!/usr/bin/env bash
#
# Build tests for the S42B v2 (STM32F103)
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_enable ENABLE_OLED ENABLE_CAN ENABLE_SERIAL ENABLE_STALLFAULT ENABLE_DYNAMIC_CURRENT
exec_test $1 $2 "OLED, CAN, Serial, StallFault, Dynamic Current" "$3"

restore_configs
opt_enable ENABLE_OLED ENABLE_SERIAL ENABLE_STALLFAULT ENABLE_OVERTEMP_PROTECTION
opt_disable ENABLE_CAN ENABLE_DYNAMIC_CURRENT
exec_test $1 $2 "OLED, Serial, Stallfault, Overtemp" "$3"

restore_configs
opt_disable ENABLE_OLED ENABLE_CAN ENABLE_SERIAL ENABLE_STALLFAULT ENABLE_DYNAMIC_CURRENT ENABLE_OVERTEMP_PROTECTION
exec_test $1 $2 "No extra options" "$3"